In [10]:
my_list = [1,2,3]
my_list[1]

2

In [11]:
import numpy as np

In [13]:
arr = np.array(my_list)

In [14]:
arr

array([1, 2, 3])

In [15]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(5,21,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(2)

array([0.32653352, 0.85549963])

In [30]:
np.random.rand(3,3)

array([[0.67317006, 0.9755605 , 0.49488   ],
       [0.78935586, 0.53257223, 0.07123407],
       [0.1897668 , 0.2882051 , 0.14444891]])

In [33]:
np.random.randn(4,4)

array([[-1.11199604,  2.25342163,  0.87838956, -1.68100002],
       [-0.18331805, -1.74264985,  1.03837834,  0.58088855],
       [-0.37365236,  0.15214919, -1.08772928, -1.43372956],
       [-0.11204653,  0.58076004,  0.2866942 ,  1.18284937]])

In [49]:
np.random.randint(1,50,5)

array([41, 42, 22, 47, 18])

In [50]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr.reshape(2,5)

array([[ 8, 43, 38, 32,  4],
       [24, 22, 35,  1, 14]])

In [54]:
ranarr

array([ 8, 43, 38, 32,  4, 24, 22, 35,  1, 14])

In [55]:
ranarr.max()

43

In [56]:
ranarr.min()

1

In [58]:
ranarr.argmin()

8

In [59]:
arr.shape

(25,)

In [60]:
arr.reshape(5,5).shape

(5, 5)

In [61]:
arr.dtype

dtype('int64')

In [62]:
ranarr.dtype

dtype('int64')

In [63]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [70]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [73]:
arr_2d[0,1]

10

In [74]:
arr2s = np.zeros((10,10))

In [81]:
for i in range(0,10):
    arr2s[i] = i
    
arr2s

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [82]:
arr2s[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [83]:
arr = np.arange(1,11)

In [84]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [86]:
bool_arr = arr > 4

In [87]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
arr[arr <= 3]

array([1, 2, 3])

In [104]:
arr_2d = np.arange(50).reshape(5,10)

In [105]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [127]:
arr_2d[1:2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])